language: haskell
install:
  - cabal install --only-dependencies --enable-tests --force-reinstalls
script:
  - cabal configure --enable-tests && cabal build && cabal install && ./dist/build/spec/spec
